version: "3.9"

services:
  pipelines:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost:8082/pipelines:v0.0.1
    #restart: always
    network_mode: host
    env_file:
      - ./.env
    logging:
      driver: json-file
      options:
        max-size: 500m
    environment:
      - TZ=America/Sao_Paulo