version: "3.9"

services:
  capture_agent:
    build:
      context: .
      dockerfile: Dockerfile
    #image: 157.230.117.123:8882/sippulse-capture-agent:v2.0.homolog
    restart: always
    network_mode: host
    env_file:
      - ./.env
    logging:
      driver: json-file
      options:
        max-size: 500m
    environment:
      - TZ=America/Sao_Paulo