version: '3'

volumes:
  data:

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: 500m
    env_file:
      - ./.env
    environment:
      - TZ=America/Sao_Paulo


