version: '3'

volumes:
  data:

services:
  app:
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    image:  localhost:8082/results_api:v0.0.1
    volumes:
      - .:/src
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: 500m
    env_file:
      - ./.env
    environment:
      - TZ=America/Sao_Paulo


